<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Perfume;
use App\Functions\Helpers;

class PerfumeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $perfumes = [
            [   
                "name" => "Eternity Moment",    
                "cover_img" => "perfume/ck-eternitymoment.jpg",    
                "brand_id" => 1,
                "quantity" => 120,
                "price" => "25.99",
                "show" => true,         
            ],            
            [   
                "name" => "BE",    
                "cover_img" => "perfume/ck-be.jpg",    
                "brand_id" => 1,
                "quantity" => 120,
                "price" => "34.99",
                "show" => true,         
            ],            
            [   
                "name" => "In2u",    
                "cover_img" => "perfume/ck-in2u.jpg",    
                "brand_id" => 1,
                "quantity" => 100,
                "price" => "45.99",
                "show" => false,         
            ],            
            [   
                "name" => "One",    
                "cover_img" => "perfume/ck-one.jpg",    
                "brand_id" => 1,
                "quantity" => 150,
                "price" => "60.99",
                "show" => false,         
            ],            
            [   
                "name" => "Everyone",    
                "cover_img" => "perfume/ck-everyone.jpg",    
                "brand_id" => 1,
                "quantity" => 100,
                "price" => "48.75",
                "show" => true,         
            ],            
            [   
                "name" => "Summer Daze",    
                "cover_img" => "perfume/ck-summerdaze.jpg",    
                "brand_id" => 1,
                "quantity" => 80,
                "price" => "26.99",
                "show" => false,         
            ],            
            [   
                "name" => "Euphoria",    
                "cover_img" => "perfume/ck-euphoria.jpg",    
                "brand_id" => 1,
                "quantity" => 120,
                "price" => "36.99",
                "show" => true,         
            ],            
            [   
                "name" => "Obsession",    
                "cover_img" => "perfume/ck-obsession.jpg",    
                "brand_id" => 1,
                "quantity" => 150,
                "price" => "80.98",
                "show" => true,         
            ],            
            [   
                "name" => "Free",    
                "cover_img" => "perfume/ck-free.jpg",    
                "brand_id" => 1,
                "quantity" => 120,
                "price" => "37.49",
                "show" => true,         
            ],            
            [   
                "name" => "One gold",    
                "cover_img" => "perfume/ck-onegold.jpg",    
                "brand_id" => 1,
                "quantity" => 100,
                "price" => "70.29",
                "show" => true,         
            ],
            [   
                "name" => "SI",    
                "cover_img" => "perfume/armani-si.jpg",    
                "brand_id" => 2,
                "quantity" => 50,
                "price" => "29.99",
                "show" => true,         
            ],            
            [   
                "name" => "Acqua di Giò",    
                "cover_img" => "perfume/armani-acquadigio.jpg",    
                "brand_id" => 2,
                "quantity" => 120,
                "price" => "34.99",
                "show" => true,         
            ],            
            [   
                "name" => "Acqua di Gioia",    
                "cover_img" => "perfume/armani-acquadigioia.jpg",    
                "brand_id" => 2,
                "quantity" => 100,
                "price" => "48.77",
                "show" => false,         
            ],            
            [   
                "name" => "Ocean di Gioia",    
                "cover_img" => "perfume/armani-oceandigioia.jpg",    
                "brand_id" => 2,
                "quantity" => 150,
                "price" => "60.99",
                "show" => false,         
            ],            
            [   
                "name" => "Terra di Gioia",    
                "cover_img" => "perfume/armani-terradigioia.jpg",    
                "brand_id" => 2,
                "quantity" => 100,
                "price" => "48.75",
                "show" => true,         
            ],            
            [   
                "name" => "My Way",    
                "cover_img" => "perfume/armani-myway.jpg",    
                "brand_id" => 2,
                "quantity" => 80,
                "price" => "26.99",
                "show" => false,         
            ],            
            [   
                "name" => "Code",    
                "cover_img" => "perfume/armani-code.jpg",    
                "brand_id" => 2,
                "quantity" => 120,
                "price" => "36.99",
                "show" => true,         
            ],            
            [   
                "name" => "Stronger with You",    
                "cover_img" => "perfume/armani-strongerwithyou.jpg",    
                "brand_id" => 2,
                "quantity" => 150,
                "price" => "80.98",
                "show" => true,         
            ],            
            [   
                "name" => "Eau de nuit",    
                "cover_img" => "perfume/armani-eaudenuit.jpg",    
                "brand_id" => 2,
                "quantity" => 120,
                "price" => "37.49",
                "show" => true,         
            ],            
            [   
                "name" => "Eau d'aromes",    
                "cover_img" => "perfume/armani-eaudaromes.jpg",    
                "brand_id" => 2,
                "quantity" => 100,
                "price" => "70.29",
                "show" => true,         
            ],
            [
                "name" => "Terre d'Hermes",
                "cover_img" => "perfume/hermes-terredhermes.jpg",
                "brand_id" => 3,
                "quantity" => 50,
                "price" => "19.99",
                "show" => true,
            ],
            [
                "name" => "H24",
                "cover_img" => "perfume/hermes-h24.jpg",
                "brand_id" => 3,
                "quantity" => 100,
                "price" => "45.79",
                "show" => false,
            ],
            [
                "name" => "Eau Givrée",
                "cover_img" => "perfume/hermes-eaugivree.jpg",
                "brand_id" => 3,
                "quantity" => 100,
                "price" => "30.46",
                "show" => true,
            ],
            [
                "name" => "Intense Vetivér",
                "cover_img" => "perfume/hermes-intensevetiver.jpg",
                "brand_id" => 3,
                "quantity" => 100,
                "price" => "22.46",
                "show" => false,
            ],
            [
                "name" => "Twilly",
                "cover_img" => "perfume/hermes-twilly.jpg",
                "brand_id" => 3,
                "quantity" => 100,
                "price" => "30.35",
                "show" => true,
            ],
            [
                "name" => "Voyage",
                "cover_img" => "perfume/hermes-voyage.jpg",
                "brand_id" => 3,
                "quantity" => 100,
                "price" => "48.58",
                "show" => true,
            ],
            [
                "name" => "Un Jardin Sur Le Nil",
                "cover_img" => "perfume/hermes-jardinsurlenil.jpg",
                "brand_id" => 3,
                "quantity" => 100,
                "price" => "41.99",
                "show" => true,
            ],
            [
                "name" => "Un Jardin Sur Le Toit",
                "cover_img" => "perfume/hermes-jardinsurletoit.jpg",
                "brand_id" => 3,
                "quantity" => 60,
                "price" => "64.89",
                "show" => true,
            ],
            [
                "name" => "Un Jardin Après la Mousson",
                "cover_img" => "perfume/hermes-jardinmousson.jpg",
                "brand_id" => 3,
                "quantity" => 80,
                "price" => "32.35",
                "show" => false,
            ],
            [
                "name" => "Un Jardin Sur La Lagune",
                "cover_img" => "perfume/hermes-jardinlagune.jpg",
                "brand_id" => 3,
                "quantity" => 120,
                "price" => "37.55",
                "show" => true,
            ],
            [
                "name" => "Light Blue",
                "cover_img" => "perfume/deg-lightblue.jpg",
                "brand_id" => 4,
                "quantity" => 100,
                "price" => "37.99",
                "show" => true,
            ],
            [
                "name" => "Light Blue Intense",
                "cover_img" => "perfume/deg-lightblueintense.jpg",
                "brand_id" => 4,
                "quantity" => 100,
                "price" => "57.39",
                "show" => true,
            ],
            [
                "name" => "Dolce",
                "cover_img" => "perfume/deg-dolce.jpg",
                "brand_id" => 4,
                "quantity" => 100,
                "price" => "61.14",
                "show" => true,
            ],
            [
                "name" => "Dolce Shine",
                "cover_img" => "perfume/deg-dolceshine.jpg",
                "brand_id" => 4,
                "quantity" => 120,
                "price" => "38.99",
                "show" => false,
            ],
            [
                "name" => "The One",
                "cover_img" => "perfume/deg-theone.jpg",
                "brand_id" => 4,
                "quantity" => 100,
                "price" => "51.99",
                "show" => true,
            ],
            [
                "name" => "The Only One",
                "cover_img" => "perfume/deg-theonlyone.jpg",
                "brand_id" => 4,
                "quantity" => 150,
                "price" => "80.79",
                "show" => true,
            ],
            [
                "name" => "L'Imperatrice",
                "cover_img" => "perfume/deg-limperatrice.jpg",
                "brand_id" => 4,
                "quantity" => 80,
                "price" => "45.49",
                "show" => false,
            ],
            [
                "name" => "K",
                "cover_img" => "perfume/deg-k.jpg",
                "brand_id" => 4,
                "quantity" => 150,
                "price" => "99.99",
                "show" => true,
            ],
            [
                "name" => "Pour Homme",
                "cover_img" => "perfume/deg-pourhomme.jpg",
                "brand_id" => 4,
                "quantity" => 100,
                "price" => "53.27",
                "show" => false,
            ],
            [
                "name" => "The One For Men",
                "cover_img" => "perfume/deg-theoneformen.jpg",
                "brand_id" => 4,
                "quantity" => 100,
                "price" => "27.99",
                "show" => true,
            ],
            [
                "name" => "Fame",
                "cover_img" => "perfume/paco-fame.jpg",
                "brand_id" => 5,
                "quantity" => 80,
                "price" => "38.99",
                "show" => true,
            ],
            [
                "name" => "Olympéa",
                "cover_img" => "perfume/paco-olympea.jpg",
                "brand_id" => 5,
                "quantity" => 120,
                "price" => "32.99",
                "show" => true,
            ],
            [
                "name" => "Lady Milion",
                "cover_img" => "perfume/paco-ladymilion.jpg",
                "brand_id" => 5,
                "quantity" => 150,
                "price" => "50.25",
                "show" => false,
            ],
            [
                "name" => "Lady Milion Royal",
                "cover_img" => "perfume/paco-ladymilionroyal.jpg",
                "brand_id" => 5,
                "quantity" => 100,
                "price" => "65.78",
                "show" => true,
            ],
            [
                "name" => "Phantom",
                "cover_img" => "perfume/paco-phantom.jpg",
                "brand_id" => 5,
                "quantity" => 100,
                "price" => "72.99",
                "show" => true,
            ],
            [
                "name" => "Fabulous",
                "cover_img" => "perfume/paco-fabulous.jpg",
                "brand_id" => 5,
                "quantity" => 80,
                "price" => "44.25",
                "show" => true,
            ],
            [
                "name" => "One Milion",
                "cover_img" => "perfume/paco-onemilion.jpg",
                "brand_id" => 5,
                "quantity" => 120,
                "price" => "61.99",
                "show" => false,
            ],
            [
                "name" => "Invictus",
                "cover_img" => "perfume/paco-invictus.jpg",
                "brand_id" => 5,
                "quantity" => 100,
                "price" => "50.19",
                "show" => true,
            ], 
            [
                "name" => "One Milion Lucky",
                "cover_img" => "perfume/paco-onemilionlucky.jpg",
                "brand_id" => 5,
                "quantity" => 80,
                "price" => "35.99",
                "show" => false,
            ],
            [
                "name" => "Pure XS",
                "cover_img" => "perfume/paco-purexs.jpg",
                "brand_id" => 5,
                "quantity" => 30,
                "price" => "43.99",
                "show" => true,
            ],
        ];

        foreach ($perfumes as $perfume) {
            $newperfume = new Perfume();
            $newperfume->name = $perfume['name'];
            $newperfume->slug = Helpers::generateSlug($newperfume->name);
            $newperfume->quantity = $perfume['quantity'];
            $newperfume->brand_id = $perfume['brand_id'];
            $newperfume->cover_img = $perfume['cover_img'];
            $newperfume->price = $perfume['price'];
            $newperfume->show = $perfume['show'];

            $newperfume->save();
        }
    }
};
